backend:
  name: git-gateway
  branch: cms-content

media_folder: /media
public_folder: /static

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'static/content/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - { label: Heading, name: heading, widget: string }
